theme: jekyll-theme-minimal
title: Paul Greenwood - Software Developer
description: Software developer specializing in web development and full-stack applications. Check out my projects and get in touch!

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
